name: Build

on:
  push:
    tags: ["*-rc*"]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
        - "2.6"
        toolchain:
        - "stable"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        default: true
    - name: Set LD_LIBRARY_PATH
      run: echo LD_LIBRARY_PATH=$(ruby -e 'print RbConfig::CONFIG["libdir"]') >> $GITHUB_ENV
    - name: Set up Cargo cache
      uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: cargo-cache-${{ steps.rust-toolchain.outputs.rustc_hash }}-${{ hashFiles('ext/datafusion_ruby/Cargo.lock') }}
    - name: Build
      run: make build
    - name: Archive Artifact
      uses: actions/upload-artifact@v3
      with:
        path: "*.gem"
        # name: "arrow-datafusion-x.y.z.gem"
