# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: CI

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rat:
    name: Release Audit Tool (RAT)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: datafusion-ruby
      - name: Checkout Arrow
        uses: actions/checkout@v3
        with:
          path: arrow
          repository: apache/arrow
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Setup Archery
        run: |
          pip install -e arrow/dev/archery[lint]
      - name: Run RAT
        run: |
          cd datafusion-ruby && archery lint --rat

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Prettier
        run: |
          npx prettier --check "**/*.md"

  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '3.1'
        runs-on:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3

      # Install datafusion-c-glib
      # We can use packages once datafusion-c-glib is released.
      - uses: actions/checkout@v3
        with:
          repository: 'datafusion-contrib/datafusion-c'
          path: datafusion-c
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Prepare on Ubuntu
        if: |
          matrix.runs-on == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y -V \
            ca-certificates \
            lsb-release \
            wget
          wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt install -y -V \
            ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt update
          sudo apt install -y -V \
            libarrow-glib-dev \
            libgirepository1.0-dev \
            ninja-build
          pip install meson
      - name: Prepare on macOS
        if: |
          matrix.runs-on == 'macos-latest'
        run: |
          brew update --preinstall
          brew bundle --file=datafusion-c/Brewfile
      - uses: actions-rs/toolchain@v1
        id: rust-toolchain
        with:
          override: true
          toolchain: stable
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: cargo-test-${{ matrix.runs-on }}-${{ steps.rust-toolchain.outputs.rustc_hash }}-${{ hashFiles('datafusion-c/**/Cargo.toml') }}
      - name: Install cargo-c
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-c
      - name: Setup
        run: |
          meson setup \
            --libdir=lib \
            --prefix=$PWD/local \
            datafusion-c-build \
            datafusion-c
      - name: Build
        run: |
          ninja -C datafusion-c-build
      - name: Install
        run: |
          ninja -C datafusion-c-build install

      # datafusion-ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Test
        run: |
          export DYLD_LIBRARY_PATH=${PWD}/local/lib:${DYLD_LIBRARY_PATH}
          export GI_TYPELIB_PATH=${PWD}/local/lib/girepository-1.0:${GI_TYPELIB_PATH}
          export LD_LIBRARY_PATH=${PWD}/local/lib:${LD_LIBRARY_PATH}
          bundle exec test/run.rb
